"""add_route_models

Revision ID: 281a07116c51
Revises: 3607cc80012d
Create Date: 2026-03-23 22:39:41.623805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281a07116c51'
down_revision: Union[str, None] = '3607cc80012d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_city_id'), 'routes', ['city_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_slug'), 'routes', ['slug'], unique=True)
    op.create_index(op.f('ix_routes_title'), 'routes', ['title'], unique=False)
    op.create_table('route_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_places_id'), 'route_places', ['id'], unique=False)
    op.create_index(op.f('ix_route_places_place_id'), 'route_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_route_places_route_id'), 'route_places', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_places_route_id'), table_name='route_places')
    op.drop_index(op.f('ix_route_places_place_id'), table_name='route_places')
    op.drop_index(op.f('ix_route_places_id'), table_name='route_places')
    op.drop_table('route_places')
    op.drop_index(op.f('ix_routes_title'), table_name='routes')
    op.drop_index(op.f('ix_routes_slug'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_city_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
