"""add_place_schedule_model

Revision ID: 3fb51e7943f5
Revises: 281a07116c51
Create Date: 2026-03-23 23:39:54.196577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb51e7943f5'
down_revision: Union[str, None] = '281a07116c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_schedules_id'), 'place_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_place_schedules_place_id'), 'place_schedules', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_schedules_weekday'), 'place_schedules', ['weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_schedules_weekday'), table_name='place_schedules')
    op.drop_index(op.f('ix_place_schedules_place_id'), table_name='place_schedules')
    op.drop_index(op.f('ix_place_schedules_id'), table_name='place_schedules')
    op.drop_table('place_schedules')
    # ### end Alembic commands ###
