"""add_place_tag_model

Revision ID: ac1e9bce72eb
Revises: 3000b4f577bc
Create Date: 2026-03-23 22:10:20.435266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1e9bce72eb'
down_revision: Union[str, None] = '3000b4f577bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_tags_id'), 'place_tags', ['id'], unique=False)
    op.create_index(op.f('ix_place_tags_place_id'), 'place_tags', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_tags_tag_id'), 'place_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_tags_tag_id'), table_name='place_tags')
    op.drop_index(op.f('ix_place_tags_place_id'), table_name='place_tags')
    op.drop_index(op.f('ix_place_tags_id'), table_name='place_tags')
    op.drop_table('place_tags')
    # ### end Alembic commands ###
