#!/usr/bin/env python3
"""Render compact CI test summaries for Telegram and GitHub Actions.

The script consumes JUnit XML generated by pytest/Vitest and produces a concise
human-readable report with totals, failed tests and a small text visualization.
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class FailedTest:
    """Single failed test item extracted from JUnit XML."""

    classname: str
    name: str
    kind: str
    message: str


@dataclass
class TestSummary:
    """Aggregated test run metrics."""

    total: int = 0
    failures: int = 0
    errors: int = 0
    skipped: int = 0
    time_seconds: float = 0.0
    failed_tests: list[FailedTest] = field(default_factory=list)
    suite_failures: dict[str, int] = field(default_factory=dict)

    @property
    def failed(self) -> int:
        """Return failed + errored tests."""
        return self.failures + self.errors

    @property
    def passed(self) -> int:
        """Return passed tests."""
        return max(0, self.total - self.failed - self.skipped)

    @property
    def pass_rate(self) -> float:
        """Return pass rate in range 0..1."""
        if self.total <= 0:
            return 0.0
        return self.passed / self.total


def _safe_int(value: str | None) -> int:
    """Parse XML integer attributes."""
    try:
        return int(value or "0")
    except ValueError:
        return 0


def _safe_float(value: str | None) -> float:
    """Parse XML float attributes."""
    try:
        return float(value or "0")
    except ValueError:
        return 0.0


def parse_junit(path: Path) -> TestSummary:
    """Parse JUnit XML into aggregated summary."""
    summary = TestSummary()
    if not path.exists():
        return summary

    root = ET.parse(path).getroot()
    suites = [root] if root.tag == "testsuite" else list(root.findall("testsuite"))

    # Some tools nest testsuites. Include direct descendants and nested suites.
    if root.tag == "testsuites":
        suites = list(root.iter("testsuite"))

    for suite in suites:
        summary.total += _safe_int(suite.attrib.get("tests"))
        summary.failures += _safe_int(suite.attrib.get("failures"))
        summary.errors += _safe_int(suite.attrib.get("errors"))
        summary.skipped += _safe_int(suite.attrib.get("skipped"))
        summary.time_seconds += _safe_float(suite.attrib.get("time"))

        for case in suite.findall("testcase"):
            failure = case.find("failure")
            error = case.find("error")
            node = failure if failure is not None else error
            if node is None:
                continue

            classname = case.attrib.get("classname", suite.attrib.get("name", "unknown"))
            name = case.attrib.get("name", "unknown")
            kind = "failure" if failure is not None else "error"
            message = (node.attrib.get("message") or (node.text or "")).strip().replace("\n", " ")
            message = textwrap.shorten(message, width=140, placeholder="…")
            summary.failed_tests.append(FailedTest(classname=classname, name=name, kind=kind, message=message))
            suite_key = classname.split(".")[0] if classname else suite.attrib.get("name", "unknown")
            summary.suite_failures[suite_key] = summary.suite_failures.get(suite_key, 0) + 1

    # If the root testsuites already has totals and child suites were absent, use root attributes.
    if summary.total == 0 and root.tag == "testsuites":
        summary.total = _safe_int(root.attrib.get("tests"))
        summary.failures = _safe_int(root.attrib.get("failures"))
        summary.errors = _safe_int(root.attrib.get("errors"))
        summary.skipped = _safe_int(root.attrib.get("skipped"))
        summary.time_seconds = _safe_float(root.attrib.get("time"))

    return summary


def format_duration(seconds: float) -> str:
    """Format seconds as compact duration."""
    minutes = int(seconds // 60)
    rest = int(seconds % 60)
    if minutes <= 0:
        return f"{rest}s"
    return f"{minutes}m {rest}s"


def progress_bar(rate: float, width: int = 12) -> str:
    """Render a unicode mini progress bar."""
    filled = round(max(0.0, min(1.0, rate)) * width)
    return "🟩" * filled + "⬜" * (width - filled)


def render_message(summary: TestSummary, args: argparse.Namespace) -> str:
    """Render Telegram/GitHub summary text."""
    status_icon = "✅" if args.exit_code == 0 and summary.failed == 0 else "❌"
    status_text = "PASSED" if status_icon == "✅" else "FAILED"
    run_url = f"{os.getenv('GITHUB_SERVER_URL', 'https://github.com')}/{os.getenv('GITHUB_REPOSITORY', '')}/actions/runs/{os.getenv('GITHUB_RUN_ID', '')}"
    commit = os.getenv("GITHUB_SHA", "unknown")
    commit_short = commit[:7] if commit != "unknown" else commit

    lines = [
        f"{status_icon} City Go {args.job_name} {status_text}",
        f"Run type: {args.run_type}",
        f"Run: #{os.getenv('GITHUB_RUN_NUMBER', 'unknown')} attempt {os.getenv('GITHUB_RUN_ATTEMPT', '1')}",
        f"Branch: {os.getenv('GITHUB_REF_NAME', 'unknown')}",
        f"Commit: {commit_short}",
        "",
        "Summary:",
        f"Total: {summary.total}",
        f"Passed: {summary.passed}",
        f"Failed: {summary.failed} ({summary.failures} failures, {summary.errors} errors)",
        f"Skipped: {summary.skipped}",
        f"Duration: {format_duration(summary.time_seconds)}",
        "",
        f"Pass rate: {summary.pass_rate * 100:.1f}%",
        progress_bar(summary.pass_rate),
    ]

    if summary.suite_failures:
        lines.append("")
        lines.append("Failed suites:")
        for suite, count in sorted(summary.suite_failures.items(), key=lambda item: item[1], reverse=True)[:8]:
            lines.append(f"- {suite}: {count}")

    if summary.failed_tests:
        lines.append("")
        lines.append("Top failed tests:")
        for index, failed in enumerate(summary.failed_tests[:10], start=1):
            lines.append(f"{index}. {failed.classname}::{failed.name}")
            if failed.message:
                lines.append(f"   {failed.message}")

    lines.extend([
        "",
        f"Allure/JUnit artifacts: {args.artifact_hint}",
        f"GitHub: {run_url}",
    ])
    return "\n".join(lines)


def append_step_summary(message: str) -> None:
    """Append markdown summary to GitHub step summary when available."""
    summary_path = os.getenv("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return
    with Path(summary_path).open("a", encoding="utf-8") as summary_file:
        summary_file.write("```text\n")
        summary_file.write(message)
        summary_file.write("\n```\n")


def main() -> int:
    """CLI entrypoint."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--junit", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--job-name", required=True)
    parser.add_argument("--run-type", required=True)
    parser.add_argument("--artifact-hint", default="uploaded in workflow artifacts")
    parser.add_argument("--exit-code", required=True, type=int)
    args = parser.parse_args()

    summary = parse_junit(args.junit)
    message = render_message(summary, args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(message, encoding="utf-8")
    append_step_summary(message)
    print(message)
    return args.exit_code


if __name__ == "__main__":
    sys.exit(main())
