import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { adminGet, adminPost } from './adminApi'
import type { AdminImportJob, AdminImportJobsResponse } from './adminTypes'
import { AdminEmpty, AdminError, AdminLoading } from './shared/AdminStates'

const STATUS_LABELS: Record<string, string> = { success: 'Завершён', success_with_warnings: 'Завершён с предупреждениями', partial_success: 'Частично завершён', imported: 'Завершён', queued: 'В очереди', importing: 'В очереди', failed: 'Ошибка', import_failed: 'Ошибка', running: 'Выполняется', review_required: 'На проверке', cancelled: 'Отменён', published: 'Опубликован' }
type AdminActionResponse = { message?: string }
const detailLine = (label: string, value: unknown) => value === null || value === undefined || value === '' ? null : <p>{label}: <strong>{String(value)}</strong></p>

export const AdminImportJobsPage = () => {
  const [params, setParams] = useSearchParams(); const cityFilter = params.get('city') ?? ''; const jobFilter = params.get('job') ?? ''
  const [items, setItems] = useState<AdminImportJob[]>([]); const [selected, setSelected] = useState<AdminImportJob | null>(null); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState<number | null>(null); const [allBusy, setAllBusy] = useState(false)
  const reload = useCallback(() => { setLoading(true); adminGet<AdminImportJobsResponse>('/admin/import-jobs?limit=100').then((r) => { setItems(r.items); setTotal(r.total) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  const loadDetail = useCallback((cityId: number) => { adminGet<AdminImportJob>(`/admin/import-jobs/${cityId}`).then(setSelected).catch((e: Error) => setError(e.message)) }, [])
  useEffect(() => { reload() }, [reload])
  useEffect(() => { if (!items.length) return; const match = jobFilter ? items.find((item) => String(item.job_id ?? '') === jobFilter) : cityFilter ? items.find((item) => item.city_slug === cityFilter) : undefined; if (match) loadDetail(match.city_id) }, [items, jobFilter, cityFilter, loadDetail])
  const visibleItems = useMemo(() => cityFilter ? items.filter((item) => item.city_slug === cityFilter) : items, [items, cityFilter])
  const selectDetail = (job: AdminImportJob) => { const next = new URLSearchParams(params); next.set('city', job.city_slug); if (job.job_id != null) next.set('job', String(job.job_id)); else next.set('detail', String(job.city_id)); setParams(next); loadDetail(job.city_id) }
  const closeDetail = () => { const next = new URLSearchParams(params); next.delete('job'); next.delete('detail'); setParams(next); setSelected(null) }
  const clearFilter = () => { const next = new URLSearchParams(params); next.delete('city'); next.delete('job'); next.delete('detail'); setParams(next); setSelected(null) }
  const runAction = async (cityId: number, path: string, label: string) => { if (!window.confirm(`${label}? Действие запустит фоновую операцию по выбранному городу.`)) return; setBusy(cityId); setError(null); setNotice(null); try { const response = await adminPost<AdminActionResponse>(path, {}); setNotice(response.message ?? 'Действие выполнено.'); reload(); loadDetail(cityId) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setBusy(null) } }
  const runAll = async () => { if (!window.confirm('Собрать и обогатить все города? Для каждого города будет поставлена отдельная фоновая задача.')) return; setAllBusy(true); setError(null); try { const response = await adminPost<AdminActionResponse>('/admin/import-jobs/enrich-all', {}); setNotice(response.message ?? 'Полный pipeline поставлен в очередь.'); reload() } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setAllBusy(false) } }
  const progressPct = (job: AdminImportJob) => (job.total_items ?? 0) > 0 ? Math.min(100, Math.round(((job.processed_items ?? 0) / (job.total_items ?? 1)) * 100)) : null
  return <div>
    <h2 className="admin-page-title">Сбор и обогащение ({cityFilter ? visibleItems.length : total})</h2><p className="admin-page-subtitle">Каждый запуск имеет URL по городу и job ID; из деталей доступны места, качество, логи и аудит.</p>
    <section className="admin-help-panel"><div className="admin-help-title">Полный запуск для всех городов</div><button type="button" className="admin-btn" disabled={allBusy || items.length === 0} onClick={() => void runAll()}>{allBusy ? 'Ставим задачи…' : 'Собрать и обогатить все города'}</button>{cityFilter && <button type="button" className="admin-btn" onClick={clearFilter}>Показать все города</button>}</section>
    {notice && <p className="admin-success-text">{notice}</p>}{error && <AdminError message={error} />}{loading ? <AdminLoading /> : visibleItems.length === 0 ? <AdminEmpty message="Задач по выбранному фильтру нет" /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Город</th><th>Запуск</th><th>Шаг</th><th>Прогресс</th><th>Мест</th><th>Действия</th></tr></thead><tbody>{visibleItems.map((job) => { const pct = progressPct(job); return <tr key={job.id} className={job.is_stalled ? 'admin-row-warning' : ''}><td><Link to={`/admin/cities/${job.city_slug}?tab=import`}>{job.city_name}</Link><div className="admin-muted">{job.city_slug}</div></td><td><button className="admin-btn admin-btn-sm" onClick={() => selectDetail(job)}>#{job.job_id ?? 'текущий'} →</button><div className="admin-muted">{job.created_at ? new Date(job.created_at).toLocaleString('ru-RU') : ''}</div></td><td><span className={`admin-badge pub-${job.status.includes('fail') ? 'hidden' : job.status === 'running' ? 'needs_review' : 'published'}`}>{job.current_step_label ?? STATUS_LABELS[job.status] ?? job.status}</span>{job.is_stalled && <div className="admin-error-text">Возможно зависла</div>}</td><td>{pct !== null ? `${pct}% (${job.processed_items ?? 0}/${job.total_items ?? 0})` : '—'}</td><td><Link to={`/admin/places?city=${job.city_slug}`}>{job.places_total}</Link><div className="admin-muted">на сайте: {job.places_published}</div></td><td className="admin-actions-cell"><button type="button" className="admin-btn admin-btn-sm" onClick={() => selectDetail(job)}>Детали</button>{job.can_run && <button type="button" className="admin-btn admin-btn-sm" disabled={busy === job.city_id} onClick={() => void runAction(job.city_id, `/admin/import-jobs/${job.city_id}/run`, 'Собрать и обогатить город')}>Запустить</button>}{job.can_retry && <button type="button" className="admin-btn admin-btn-sm" disabled={busy === job.city_id} onClick={() => void runAction(job.city_id, `/admin/import-jobs/${job.city_id}/retry`, 'Повторить запуск')}>Повторить</button>}</td></tr> })}</tbody></table></div>}
    {selected && <div className="admin-detail-panel"><h3>{selected.city_name} · запуск #{selected.job_id ?? 'текущий'}</h3><p>Шаг: <strong>{selected.current_step_label ?? STATUS_LABELS[selected.status] ?? selected.status}</strong></p><p>Обработано: {selected.processed_items ?? 0}/{selected.total_items ?? 0} · успешно: {selected.successful_items ?? 0} · ошибок: {selected.failed_items ?? 0}</p><p>Найдено: {selected.places_found ?? 0} · сохранено: {selected.places_saved ?? 0} · в городе: {selected.places_total}</p>{selected.last_error && <p className="admin-error-text">Ошибка: {selected.last_error}</p>}{selected.step_details && <details open><summary>Детали текущего шага</summary>{detailLine('Найдено мест', selected.step_details.places_found)}{detailLine('Сохранено мест', selected.step_details.places_saved)}{detailLine('Всего к обработке', selected.step_details.total_items)}{detailLine('Обработано', selected.step_details.processed_items)}<pre>{JSON.stringify(selected.step_details, null, 2)}</pre></details>}<div className="admin-actions-cell">{selected.report_url && <Link className="admin-btn admin-btn-sm" to={selected.report_url}>Отчёт качества</Link>}{selected.logs_url ? <Link className="admin-btn admin-btn-sm" to={selected.logs_url}>Логи запуска</Link> : <Link className="admin-btn admin-btn-sm" to={`/admin/system-logs?city_slug=${selected.city_slug}&request_id=${selected.job_id ?? ''}`}>Логи запуска</Link>}<Link className="admin-btn admin-btn-sm" to={`/admin/imports/${selected.city_slug}/jobs/${selected.job_id ?? 'current'}/changes?city_id=${selected.city_id}`}>Открыть изменения</Link><Link className="admin-btn admin-btn-sm" to={`/admin/places?city=${selected.city_slug}`}>Все места</Link><Link className="admin-btn admin-btn-sm" to={`/admin/places?city=${selected.city_slug}&verification=needs_recheck`}>Изменённые места</Link><Link className="admin-btn admin-btn-sm" to={`/admin/audit?entity_type=import_job&entity_id=${selected.job_id ?? ''}`}>Аудит запуска</Link><button type="button" className="admin-btn admin-btn-sm" onClick={closeDetail}>Закрыть</button></div></div>}
  </div>
}
