import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { adminGet, adminPost } from './adminApi'
import type { AdminImportJob, AdminImportJobsResponse } from './adminTypes'
import { AdminEmpty, AdminError, AdminLoading } from './shared/AdminStates'

const STATUS_LABELS: Record<string, string> = { success: 'Завершён', success_with_warnings: 'Завершён с предупреждениями', partial_success: 'Частично завершён', imported: 'Завершён', queued: 'В очереди', importing: 'В очереди', failed: 'Ошибка', import_failed: 'Ошибка', running: 'Выполняется', review_required: 'На проверке', cancelled: 'Отменён', published: 'Опубликован', stalled: 'Завис' }
type AdminActionResponse = { message?: string }
type AnyDict = Record<string, unknown>
const asDict = (value: unknown): AnyDict => value && typeof value === 'object' && !Array.isArray(value) ? value as AnyDict : {}
const detailsOf = (job: AdminImportJob) => asDict(job.step_details)
const nested = (job: AdminImportJob, key: string) => asDict(detailsOf(job)[key])
const text = (value: unknown, fallback = '—') => value === null || value === undefined || value === '' ? fallback : String(value)
const num = (value: unknown) => typeof value === 'number' ? value : Number(value ?? 0) || 0
const detailLine = (label: string, value: unknown) => value === null || value === undefined || value === '' ? null : <p>{label}: <strong>{String(value)}</strong></p>
const isRunningLike = (job: AdminImportJob) => ['queued', 'running'].includes(job.status) || ['queued', 'running'].includes(job.current_step ?? '')
const isBlockingImportError = (job: AdminImportJob) => { const currentStep = job.current_step ?? ''; return Boolean(job.last_error && ((job.failed_items ?? 0) > 0 || job.is_stalled || job.status.includes('fail') || ['failed', 'import_failed', 'stalled'].includes(currentStep))) }
const changesUrl = (job: AdminImportJob) => `/admin/imports/${job.city_slug}/jobs/${job.job_id ?? 'current'}/changes?city_id=${job.city_id}`
const logsUrl = (job: AdminImportJob) => job.logs_url ?? `/admin/system-logs?city_slug=${job.city_slug}&request_id=${job.job_id ?? ''}`
const progressPct = (job: AdminImportJob) => (job.total_items ?? 0) > 0 ? Math.min(100, Math.round(((job.processed_items ?? 0) / (job.total_items ?? 1)) * 100)) : null
const badgeTone = (job: AdminImportJob) => job.status.includes('fail') || job.status === 'stalled' ? 'hidden' : job.status === 'running' || job.status === 'queued' ? 'needs_review' : job.launch_status === 'published' ? 'published' : 'draft'

const ImportActionButtons = ({ job, busy, onAction, onSelect }: { job: AdminImportJob, busy: number | null, onAction: (job: AdminImportJob, action: string, label: string) => void, onSelect: (job: AdminImportJob) => void }) => <div className="admin-actions-cell">
  <Link className="admin-btn admin-btn-sm" to={changesUrl(job)}>Изменения</Link>
  <button type="button" className="admin-btn admin-btn-sm" onClick={() => onSelect(job)}>Детали</button>
  <Link className="admin-btn admin-btn-sm" to={logsUrl(job)}>Логи</Link>
  {job.can_run && <button type="button" className="admin-btn admin-btn-sm" disabled={busy === job.city_id} onClick={() => onAction(job, 'run', 'Запустить сбор')}>Запустить сбор</button>}
  {job.can_retry && <button type="button" className="admin-btn admin-btn-sm" disabled={busy === job.city_id} onClick={() => onAction(job, 'retry', 'Повторить сбор')}>Повторить сбор</button>}
  {job.can_cancel && <button type="button" className="admin-btn admin-btn-sm" disabled={busy === job.city_id} onClick={() => onAction(job, 'cancel', 'Отменить сбор')}>Отменить</button>}
  {job.can_publish && <button type="button" className="admin-btn admin-btn-sm admin-btn-primary" disabled={busy === job.city_id} onClick={() => onAction(job, 'publish', 'Опубликовать город')}>Опубликовать</button>}
</div>

export const AdminImportJobsPage = () => {
  const [params, setParams] = useSearchParams(); const cityFilter = params.get('city') ?? ''; const jobFilter = params.get('job') ?? ''
  const [items, setItems] = useState<AdminImportJob[]>([]); const [selected, setSelected] = useState<AdminImportJob | null>(null); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState<number | null>(null); const [allBusy, setAllBusy] = useState(false)
  const reload = useCallback(() => { setLoading(true); adminGet<AdminImportJobsResponse>('/admin/import-jobs?limit=100').then((r) => { setItems(r.items); setTotal(r.total) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  const loadDetail = useCallback((cityId: number) => { adminGet<AdminImportJob>(`/admin/import-jobs/${cityId}`).then(setSelected).catch((e: Error) => setError(e.message)) }, [])
  useEffect(() => { reload() }, [reload])
  useEffect(() => { if (!items.length) return; const match = jobFilter ? items.find((item) => String(item.job_id ?? '') === jobFilter) : cityFilter ? items.find((item) => item.city_slug === cityFilter) : undefined; if (match) loadDetail(match.city_id) }, [items, jobFilter, cityFilter, loadDetail])
  useEffect(() => { if (!items.some(isRunningLike) && !selected) return; const timer = window.setInterval(() => { void reload(); if (selected && isRunningLike(selected)) loadDetail(selected.city_id) }, 7000); return () => window.clearInterval(timer) }, [items, selected, reload, loadDetail])
  const visibleItems = useMemo(() => cityFilter ? items.filter((item) => item.city_slug === cityFilter) : items, [items, cityFilter])
  const selectDetail = (job: AdminImportJob) => { const next = new URLSearchParams(params); next.set('city', job.city_slug); if (job.job_id != null) next.set('job', String(job.job_id)); else next.set('detail', String(job.city_id)); setParams(next); loadDetail(job.city_id) }
  const closeDetail = () => { const next = new URLSearchParams(params); next.delete('job'); next.delete('detail'); setParams(next); setSelected(null) }
  const clearFilter = () => { const next = new URLSearchParams(params); next.delete('city'); next.delete('job'); next.delete('detail'); setParams(next); setSelected(null) }
  const runAction = async (job: AdminImportJob, action: string, label: string) => { if (!window.confirm(`${label}: ${job.city_name}?`)) return; setBusy(job.city_id); setError(null); setNotice(null); try { const response = await adminPost<AdminActionResponse>(`/admin/import-jobs/${job.city_id}/${action}`, action === 'publish' ? { reason: 'admin_import_publish' } : {}); setNotice(response.message ?? 'Действие выполнено.'); reload(); loadDetail(job.city_id) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setBusy(null) } }
  const runAll = async () => { if (!window.confirm('Собрать и обогатить все города? Для каждого города будет поставлена отдельная фоновая задача.')) return; setAllBusy(true); setError(null); try { const response = await adminPost<AdminActionResponse>('/admin/import-jobs/enrich-all', {}); setNotice(response.message ?? 'Полный pipeline поставлен в очередь.'); reload() } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setAllBusy(false) } }
  return <div>
    <h2 className="admin-page-title">Сбор и обогащение ({cityFilter ? visibleItems.length : total})</h2><p className="admin-page-subtitle">Новый рабочий сценарий: OSM/import scopes собирают места, foundation-layer фиксирует качество, изменения уходят на ручную проверку, затем город публикуется.</p>
    <section className="admin-help-panel"><div className="admin-help-title">Полный запуск для всех городов</div><p className="admin-muted">HTTP-запуск только ставит задачу в очередь. Выполнение делает import-worker, экран обновляется автоматически для queued/running jobs.</p><button type="button" className="admin-btn" disabled={allBusy || items.length === 0} onClick={() => void runAll()}>{allBusy ? 'Ставим задачи…' : 'Собрать и обогатить все города'}</button>{cityFilter && <button type="button" className="admin-btn" onClick={clearFilter}>Показать все города</button>}</section>
    {notice && <p className="admin-success-text">{notice}</p>}{error && <AdminError message={error} />}{loading ? <AdminLoading /> : visibleItems.length === 0 ? <AdminEmpty message="Задач по выбранному фильтру нет" /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Город</th><th>Запуск</th><th>Шаг</th><th>Прогресс</th><th>Покрытие</th><th>Действия</th></tr></thead><tbody>{visibleItems.map((job) => { const pct = progressPct(job); const coverage = nested(job, 'data_coverage'); const contract = nested(job, 'admin_pipeline_contract'); return <tr key={job.id} className={job.is_stalled ? 'admin-row-warning' : ''}><td><Link to={`/admin/cities/${job.city_slug}?tab=import`}>{job.city_name}</Link><div className="admin-muted">{job.city_slug}</div><div className="admin-muted">{text(contract.label, 'OSM + foundation')}</div></td><td><button className="admin-btn admin-btn-sm" onClick={() => selectDetail(job)}>#{job.job_id ?? 'текущий'} →</button><div className="admin-muted">{job.created_at ? new Date(job.created_at).toLocaleString('ru-RU') : ''}</div></td><td><span className={`admin-badge pub-${badgeTone(job)}`}>{job.current_step_label ?? STATUS_LABELS[job.status] ?? job.status}</span>{isRunningLike(job) && <div className="admin-muted">автообновление 7с</div>}{job.is_stalled && <div className="admin-error-text">Возможно зависла</div>}</td><td>{pct !== null ? `${pct}% (${job.processed_items ?? 0}/${job.total_items ?? 0})` : '—'}<div className="admin-muted">найдено: {job.places_found ?? 0}, сохранено: {job.places_saved ?? 0}</div></td><td><Link to={`/admin/places?city=${job.city_slug}`}>{job.places_total}</Link><div className="admin-muted">адреса: {text(coverage.address_coverage_pct)}%</div><div className="admin-muted">фото: {text(coverage.photo_coverage_pct)}%</div><div className="admin-muted">описания: {text(coverage.description_coverage_pct)}%</div></td><td><ImportActionButtons job={job} busy={busy} onAction={runAction} onSelect={selectDetail} /></td></tr> })}</tbody></table></div>}
    {selected && <ImportJobDetail selected={selected} busy={busy} onAction={runAction} onClose={closeDetail} />}
  </div>
}

const ImportJobDetail = ({ selected, busy, onAction, onClose }: { selected: AdminImportJob, busy: number | null, onAction: (job: AdminImportJob, action: string, label: string) => void, onClose: () => void }) => {
  const coverage = nested(selected, 'data_coverage'); const changes = nested(selected, 'change_summary'); const contract = nested(selected, 'admin_pipeline_contract')
  return <div className="admin-detail-panel"><h3>{selected.city_name} · запуск #{selected.job_id ?? 'текущий'}</h3><p>Шаг: <strong>{selected.current_step_label ?? STATUS_LABELS[selected.status] ?? selected.status}</strong></p><p>Действие: <strong>{text(detailsOf(selected).admin_action_hint)}</strong></p><p>Pipeline: <strong>{text(contract.label)}</strong></p><p>{selected.next_step}</p>
    <div className="admin-metrics-grid"><div className="admin-metric-card"><div className="admin-metric-value">{selected.places_total}</div><div className="admin-metric-label">мест в городе</div></div><div className="admin-metric-card"><div className="admin-metric-value">{selected.places_published}</div><div className="admin-metric-label">на сайте</div></div><div className="admin-metric-card"><div className="admin-metric-value">{num(changes.total_changes)}</div><div className="admin-metric-label">изменений</div></div><div className="admin-metric-card"><div className="admin-metric-value">{selected.failed_items ?? 0}</div><div className="admin-metric-label">ошибок</div></div></div>
    <section className="admin-help-panel"><div className="admin-help-title">Покрытие критичными данными</div><p>Адреса: <strong>{text(coverage.address_coverage_pct)}%</strong> · без адреса: {text(coverage.without_address)}</p><p>Фото: <strong>{text(coverage.photo_coverage_pct)}%</strong> · без фото: {text(coverage.without_photo)} · кандидатов на проверку: {text(coverage.pending_photos)}</p><p>Описания: <strong>{text(coverage.description_coverage_pct)}%</strong> · без описания: {text(coverage.without_description)}</p></section>
    <section className="admin-help-panel"><div className="admin-help-title">Отчёт изменений</div><p>Новые: <strong>{text(changes.created, '0')}</strong> · обновлённые: <strong>{text(changes.updated, '0')}</strong> · на проверку: <strong>{text(changes.needs_review, '0')}</strong> · скрытые: <strong>{text(changes.hidden, '0')}</strong> · отклонённые: <strong>{text(changes.rejected, '0')}</strong> · без изменений: <strong>{text(changes.unchanged, '0')}</strong></p></section>
    <p>Обработано: {selected.processed_items ?? 0}/{selected.total_items ?? 0} · успешно: {selected.successful_items ?? 0} · ошибок: {selected.failed_items ?? 0}</p><p>Найдено: {selected.places_found ?? 0} · сохранено: {selected.places_saved ?? 0}</p>{isBlockingImportError(selected) && <p className="admin-error-text">Ошибка: {selected.last_error}</p>}{selected.last_error && !isBlockingImportError(selected) && <details><summary>Старая сохранённая ошибка</summary><p className="admin-muted">Это ошибка прошлого шага. Текущий статус: {selected.current_step_label ?? selected.status}; failed_items={selected.failed_items ?? 0}.</p><pre>{selected.last_error}</pre></details>}
    {selected.step_details && <details><summary>Технические детали pipeline</summary>{detailLine('Найдено мест', selected.step_details.places_found)}{detailLine('Сохранено мест', selected.step_details.places_saved)}{detailLine('Всего к обработке', selected.step_details.total_items)}{detailLine('Обработано', selected.step_details.processed_items)}<pre>{JSON.stringify(selected.step_details, null, 2)}</pre></details>}
    <div className="admin-actions-cell"><ImportActionButtons job={selected} busy={busy} onAction={onAction} onSelect={() => undefined} />{selected.report_url && <Link className="admin-btn admin-btn-sm" to={selected.report_url}>Отчёт качества</Link>}<Link className="admin-btn admin-btn-sm" to={`/admin/places?city=${selected.city_slug}`}>Все места</Link><Link className="admin-btn admin-btn-sm" to={`/admin/places?city=${selected.city_slug}&verification=needs_recheck`}>Изменённые места</Link><Link className="admin-btn admin-btn-sm" to={`/admin/audit?entity_type=import_job&entity_id=${selected.job_id ?? ''}`}>Аудит запуска</Link><button type="button" className="admin-btn admin-btn-sm" onClick={onClose}>Закрыть</button></div>
  </div>
}
