import { useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { adminPost } from './adminApi'
import { fetchPendingPlaceImages, type PendingPlaceImage } from '../../api/admin/placeImageReview.api'
import { AdminEmpty, AdminError, AdminLoading } from './shared/AdminStates'

export const AdminPlaceImagesPage = () => {
  const [params, setParams] = useSearchParams(); const city = params.get('city') ?? ''; const source = params.get('source') ?? ''; const imageId = Number(params.get('image_id') ?? 0)
  const [items, setItems] = useState<PendingPlaceImage[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<number | 'bulk' | null>(null); const [selected, setSelected] = useState<Set<number>>(new Set())
  const load = useCallback(async () => { setLoading(true); setError(null); try { const data = await fetchPendingPlaceImages(city || undefined, 100, 0); const filtered = data.items.filter((item) => (!source || item.source_type === source) && (!imageId || item.image_id === imageId)); setItems(filtered); setTotal(imageId || source ? filtered.length : data.total); setSelected(new Set()) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка загрузки') } finally { setLoading(false) } }, [city, source, imageId])
  useEffect(() => { void load() }, [load])
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('image_id'); setParams(next) }
  const action = async (id: number, act: 'approve' | 'reject' | 'set-primary') => { if (act === 'reject' && !window.confirm('Отклонить это фото?')) return; setBusy(id); try { await adminPost(`/admin/place-images/${id}/${act}`, act !== 'set-primary' ? {} : undefined); setItems((cur) => cur.filter((i) => i.image_id !== id)); setTotal((cur) => Math.max(0, cur - 1)) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка действия') } finally { setBusy(null) } }
  const toggle = (id: number) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next })
  const bulkAction = async (act: 'approve' | 'reject') => { const imageIds = [...selected]; if (!imageIds.length) return; if (!window.confirm(`${act === 'approve' ? 'Принять' : 'Отклонить'} ${imageIds.length} фото?`)) return; setBusy('bulk'); setError(null); try { await adminPost(`/admin/place-images/bulk/${act}`, { image_ids: imageIds }); setItems((current) => current.filter((item) => !selected.has(item.image_id))); setTotal((current) => Math.max(0, current - imageIds.length)); setSelected(new Set()) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка массового действия') } finally { setBusy(null) } }
  const sources = [...new Set(items.map((item) => item.source_type).filter(Boolean))]
  return <div>
    <h2 className="admin-page-title">Фото ({total})</h2><p className="admin-page-subtitle">Карточка ведёт к месту, источник открывается отдельно, а фильтры сохраняются в URL.</p>
    <div className="admin-tabs"><Link className="admin-tab active" to={`/admin/photos${city ? `?city=${city}` : ''}`}>На проверке ({total})</Link><Link className="admin-tab" to={`/admin/places?preset=no_photo${city ? `&city=${city}` : ''}`}>Места без фото</Link></div>
    <div className="admin-filter-card admin-filter-grid"><label className="admin-field"><span>Город</span><input value={city} onChange={(e) => update('city', e.target.value)} placeholder="slug города" /></label><label className="admin-field"><span>Источник</span><select value={source} onChange={(e) => update('source', e.target.value)}><option value="">Все источники</option>{sources.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><button className="admin-btn" onClick={() => setParams({})}>Сбросить</button><button className="admin-btn admin-btn-ok" disabled={!selected.size || busy !== null} onClick={() => void bulkAction('approve')}>Принять выбранные ({selected.size})</button><button className="admin-btn admin-btn-danger" disabled={!selected.size || busy !== null} onClick={() => void bulkAction('reject')}>Отклонить выбранные ({selected.size})</button></div>
    {error && <AdminError message={error} />}{loading ? <AdminLoading /> : items.length === 0 ? <AdminEmpty message="Очередь модерации пуста" /> : <div className="admin-image-grid">{items.map((img) => <article key={img.image_id} className="admin-image-card"><Link to={`/admin/places/${img.place_id}`}><img src={img.thumbnail_url ?? img.image_url} alt={img.place_title} className="admin-image-thumb" onError={(e) => { (e.target as HTMLImageElement).style.display = 'none' }} /></Link><div className="admin-image-info"><Link className="admin-image-title" to={`/admin/places/${img.place_id}`}>{img.place_title}</Link><div className="admin-image-meta">{img.city_slug ?? 'Город не указан'} · {img.place_category ?? 'Без категории'}</div><div className="admin-image-meta">{img.source_type} · {img.confidence != null ? `${Math.round(img.confidence * 100)}%` : 'Уверенность не указана'}</div><div className="admin-actions-cell">{img.source_url && <a className="admin-btn admin-btn-sm" href={img.source_url} target="_blank" rel="noreferrer">Открыть источник</a>}<Link className="admin-btn admin-btn-sm" to={`/admin/audit?entity_type=place_image&entity_id=${img.image_id}`}>История</Link></div></div><div className="admin-image-actions"><label><input aria-label={`Выбрать ${img.place_title}`} type="checkbox" checked={selected.has(img.image_id)} onChange={() => toggle(img.image_id)} /></label><button disabled={busy !== null} onClick={() => void action(img.image_id, 'approve')} className="admin-btn admin-btn-ok" title="Принять">✓</button><button disabled={busy !== null} onClick={() => void action(img.image_id, 'set-primary')} className="admin-btn admin-btn-sm" title="Сделать главным">⭐</button><button disabled={busy !== null} onClick={() => void action(img.image_id, 'reject')} className="admin-btn admin-btn-danger" title="Отклонить">✕</button></div></article>)}</div>}
  </div>
}
