import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { adminGet, adminPatch, adminPost, adminPut } from './adminApi'
import './AdminTaxonomy.css'

type Category = { id: number; code: string; name: string; display_name: string; description?: string; parent_id?: number; icon?: string; color_token: string; sort_order: number; is_active: boolean; is_catalog_visible: boolean; is_searchable: boolean; is_route_eligible: boolean; route_policy: string; route_contexts: string[]; places_count: number }
type Mapping = { id: number; source: string; source_key: string; source_value: string; target_category_id: number; priority: number; confidence: number; active: boolean; conditions: Record<string, unknown>; comment?: string }
type Conflict = { id: number; place_id: number; place_title?: string; conflict_type: string; severity: string; source?: string; confidence?: number; current_category_id?: number; recommended_category_id?: number; details: Record<string, unknown> }
type Batch = { id: string; status: string; preview: { count: number; examples: Array<Record<string, unknown>>; route_conflicts: number }; result?: Record<string, unknown>; rollback_result?: Record<string, unknown> }
type QualityRule = { id: number; code: string; name_ru: string; severity: string; active: boolean; blocking_publication: boolean; blocking_route_eligibility: boolean }
type TreeNode = Category & { breadcrumb: string; children: TreeNode[] }

type Tab = 'categories' | 'tree' | 'aliases' | 'rules' | 'conflicts' | 'bulk' | 'history' | 'routes'
const TABS: Array<[Tab, string]> = [['categories', 'Категории'], ['tree', 'Иерархия'], ['aliases', 'Псевдонимы'], ['rules', 'Правила классификации'], ['conflicts', 'Конфликты'], ['bulk', 'Массовая переклассификация'], ['history', 'История изменений'], ['routes', 'Настройки маршрутов']]
const POLICY_LABELS: Record<string, string> = { always_allowed: 'Всегда разрешено', allowed_by_context: 'По контексту', useful_only: 'Только полезные точки', forbidden: 'Запрещено', manual_review: 'Ручная проверка' }

export function AdminTaxonomyPage() {
  const [params, setParams] = useSearchParams()
  const tab = (params.get('tab') as Tab) || 'categories'
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const loadCategories = useCallback(async () => {
    setLoading(true); setError('')
    try { const data = await adminGet<{ items: Category[] }>('/admin/taxonomy/categories?limit=200'); setCategories(data.items) }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить категории') }
    finally { setLoading(false) }
  }, [])
  useEffect(() => { void loadCategories() }, [loadCategories])
  const selectTab = (next: Tab) => { const copy = new URLSearchParams(params); copy.set('tab', next); setParams(copy) }

  return <div className="taxonomy-page">
    <header className="admin-page-header"><div><h1 className="admin-page-title">Таксономия и качество данных</h1><p className="admin-page-subtitle">Категории, внешние сопоставления, конфликты и безопасная массовая обработка мест.</p></div></header>
    <nav className="taxonomy-tabs" aria-label="Разделы таксономии">{TABS.map(([key, label]) => <button key={key} className={`admin-tab ${tab === key ? 'active' : ''}`} onClick={() => selectTab(key)}>{label}</button>)}</nav>
    {error && <div className="admin-state admin-state-error">{error}<button className="admin-btn" onClick={() => void loadCategories()}>Повторить</button></div>}
    {loading ? <div className="admin-state">Загружаем таксономию…</div> : <>
      {tab === 'categories' && <CategoriesTab categories={categories} reload={loadCategories} />}
      {tab === 'tree' && <TreeTab reloadCategories={loadCategories} />}
      {(tab === 'aliases' || tab === 'rules') && <MappingsTab categories={categories} aliasesOnly={tab === 'aliases'} />}
      {tab === 'conflicts' && <ConflictsTab categories={categories} />}
      {tab === 'bulk' && <BulkTab categories={categories} />}
      {tab === 'history' && <HistoryTab />}
      {tab === 'routes' && <RoutePoliciesTab categories={categories} reload={loadCategories} />}
    </>}
  </div>
}

function CategoriesTab({ categories, reload }: { categories: Category[]; reload: () => Promise<void> }) {
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<Category | null>(null); const [creating, setCreating] = useState(false)
  const visible = useMemo(() => categories.filter(row => `${row.display_name} ${row.code}`.toLowerCase().includes(search.toLowerCase())), [categories, search])
  return <section><div className="taxonomy-toolbar"><input aria-label="Поиск категорий" placeholder="Поиск по названию или коду" value={search} onChange={event => setSearch(event.target.value)} /><button className="admin-btn admin-btn-primary" onClick={() => setCreating(true)}>Создать категорию</button></div>
    <div className="taxonomy-table admin-table-wrap"><table className="admin-table"><thead><tr><th>Категория</th><th>Родитель</th><th>Каталог</th><th>Маршруты</th><th>Мест</th><th>Действия</th></tr></thead><tbody>{visible.map(row => <tr key={row.id}><td><strong>{row.display_name}</strong><small>{row.description || 'Описание не задано'}</small></td><td>{categories.find(item => item.id === row.parent_id)?.display_name || 'Корневая'}</td><td>{row.is_catalog_visible ? 'Показывается' : 'Скрыта'}</td><td>{POLICY_LABELS[row.route_policy] || 'Ручная проверка'}</td><td>{row.places_count}</td><td className="admin-actions-cell"><button className="admin-btn admin-btn-sm" onClick={() => setEditing(row)}>Редактировать</button><button className="admin-btn admin-btn-sm" onClick={async () => { await adminPatch(`/admin/taxonomy/categories/${row.id}`, { is_active: !row.is_active }); await reload() }}>{row.is_active ? 'Архивировать' : 'Восстановить'}</button></td></tr>)}</tbody></table></div>
    <div className="taxonomy-mobile-list">{visible.map(row => <article className="taxonomy-card" key={row.id}><div><strong>{row.display_name}</strong><span>{POLICY_LABELS[row.route_policy]}</span></div><p>{row.description || 'Описание не задано'}</p><div className="taxonomy-card-actions"><button className="admin-btn" onClick={() => setEditing(row)}>Редактировать</button><button className="admin-btn" onClick={async () => { await adminPatch(`/admin/taxonomy/categories/${row.id}`, { is_active: !row.is_active }); await reload() }}>{row.is_active ? 'В архив' : 'Восстановить'}</button></div></article>)}</div>
    {(creating || editing) && <CategoryDialog category={editing} categories={categories} close={() => { setCreating(false); setEditing(null) }} saved={reload} />}
  </section>
}

function CategoryDialog({ category, categories, close, saved }: { category: Category | null; categories: Category[]; close: () => void; saved: () => Promise<void> }) {
  const [name, setName] = useState(category?.name || ''); const [code, setCode] = useState(category?.code || ''); const [description, setDescription] = useState(category?.description || ''); const [parentId, setParentId] = useState(category?.parent_id?.toString() || ''); const [policy, setPolicy] = useState(category?.route_policy || 'manual_review'); const [catalog, setCatalog] = useState(category?.is_catalog_visible ?? true); const [searchable, setSearchable] = useState(category?.is_searchable ?? true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const payload = { name, code, description: description || null, parent_id: parentId ? Number(parentId) : null, route_policy: policy, route_contexts: [], is_catalog_visible: catalog, is_searchable: searchable, is_route_eligible: policy !== 'forbidden', color_token: category?.color_token || 'category-default', sort_order: category?.sort_order || 0 }
    try { if (category) await adminPatch(`/admin/taxonomy/categories/${category.id}`, payload); else await adminPost('/admin/taxonomy/categories', payload); await saved(); close() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить') } finally { setSaving(false) } }
  return <div className="admin-dialog-backdrop" role="presentation"><form className="admin-dialog taxonomy-dialog" onSubmit={submit}><h3>{category ? 'Редактировать категорию' : 'Новая категория'}</h3>{error && <p className="admin-error-text">{error}</p>}<label className="admin-field">Название на русском<input required value={name} onChange={e => setName(e.target.value)} /></label><label className="admin-field">Внутренний код<input required disabled={Boolean(category)} pattern="[a-z0-9_]+" value={code} onChange={e => setCode(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '_'))} /></label><label className="admin-field">Описание<textarea value={description} onChange={e => setDescription(e.target.value)} /></label><label className="admin-field">Родитель<select value={parentId} onChange={e => setParentId(e.target.value)}><option value="">Корневая категория</option>{categories.filter(row => row.id !== category?.id).map(row => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select></label><label className="admin-field">Политика маршрутов<select value={policy} onChange={e => setPolicy(e.target.value)}>{Object.entries(POLICY_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="taxonomy-check"><input type="checkbox" checked={catalog} onChange={e => setCatalog(e.target.checked)} /> Показывать в каталоге</label><label className="taxonomy-check"><input type="checkbox" checked={searchable} onChange={e => setSearchable(e.target.checked)} /> Доступна в поиске</label><div className="taxonomy-dialog-actions"><button type="button" className="admin-btn" onClick={close}>Отмена</button><button className="admin-btn admin-btn-primary" disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></form></div>
}

function TreeTab({ reloadCategories }: { reloadCategories: () => Promise<void> }) {
  const [tree, setTree] = useState<TreeNode[]>([]); const [saving, setSaving] = useState(false); const load = useCallback(async () => setTree(await adminGet<TreeNode[]>('/admin/taxonomy/tree')), []); useEffect(() => { void load() }, [load])
  const flat = useMemo(() => flattenTree(tree), [tree]); const [dragged, setDragged] = useState<number | null>(null)
  const move = (target: number | null) => { if (dragged === null || dragged === target) return; setTree(rebuildTree(flat.map((row, index) => row.id === dragged ? { ...row, parent_id: target, sort_order: index } : row))); setDragged(null) }
  return <section className="taxonomy-split"><div className="admin-filter-card"><h2 className="admin-section-title">Управляемое дерево</h2><p className="admin-muted">Перетащите категорию на другую, чтобы сменить родителя. Перетащите в корневую область, чтобы сделать корневой.</p><div className="taxonomy-root-drop" onDragOver={e => e.preventDefault()} onDrop={() => move(null)}>Перетащить в корень</div><TreeList nodes={tree} dragged={dragged} setDragged={setDragged} move={move} /><button className="admin-btn admin-btn-primary" disabled={saving} onClick={async () => { setSaving(true); await adminPut('/admin/taxonomy/tree', { nodes: flattenTree(tree).map(({ id, parent_id, sort_order }) => ({ id, parent_id: parent_id || null, sort_order })) }); await load(); await reloadCategories(); setSaving(false) }}>Сохранить дерево</button></div><aside className="admin-help-panel"><strong>Предпросмотр</strong>{flat.map(row => <p key={row.id} className="admin-muted">{row.breadcrumb}</p>)}</aside></section>
}
function TreeList({ nodes, dragged, setDragged, move }: { nodes: TreeNode[]; dragged: number | null; setDragged: (id: number | null) => void; move: (id: number) => void }) { return <div className="taxonomy-tree">{nodes.map(node => <div key={node.id} className="taxonomy-tree-node"><button draggable onDragStart={() => setDragged(node.id)} onDragEnd={() => setDragged(null)} onDragOver={e => e.preventDefault()} onDrop={() => move(node.id)} className={dragged === node.id ? 'dragging' : ''}>{node.display_name}<span>{node.children.length} дочерних</span></button>{node.children.length > 0 && <TreeList nodes={node.children} dragged={dragged} setDragged={setDragged} move={move} />}</div>)}</div> }
function flattenTree(nodes: TreeNode[], parentId: number | null = null, crumbs: string[] = []): TreeNode[] { return nodes.flatMap((node, index) => { const current = { ...node, parent_id: parentId || undefined, sort_order: index, breadcrumb: [...crumbs, node.display_name].join(' / ') }; return [current, ...flattenTree(node.children, node.id, [...crumbs, node.display_name])] }) }
function rebuildTree(rows: TreeNode[]): TreeNode[] { const map = new Map(rows.map(row => [row.id, { ...row, children: [] as TreeNode[] }])); const roots: TreeNode[] = []; map.forEach(row => { const parent = row.parent_id ? map.get(row.parent_id) : undefined; if (parent) parent.children.push(row); else roots.push(row) }); return roots }

function MappingsTab({ categories, aliasesOnly }: { categories: Category[]; aliasesOnly: boolean }) {
  const [items, setItems] = useState<Mapping[]>([]); const [source, setSource] = useState(aliasesOnly ? 'text_alias' : 'osm'); const [key, setKey] = useState(aliasesOnly ? '__title__' : 'amenity'); const [value, setValue] = useState(''); const [categoryId, setCategoryId] = useState(''); const load = useCallback(async () => { const data = await adminGet<{ items: Mapping[] }>('/admin/taxonomy/mappings?limit=300'); setItems(data.items.filter(row => aliasesOnly ? row.source === 'text_alias' : row.source !== 'text_alias')) }, [aliasesOnly]); useEffect(() => { void load() }, [load])
  const submit = async (event: FormEvent) => { event.preventDefault(); await adminPost('/admin/taxonomy/mappings', { source, source_key: key, source_value: value, target_category_id: Number(categoryId), priority: 100, confidence: 1, active: true, conditions: {}, fallback: false }); setValue(''); await load() }
  return <section><form className="admin-filter-card taxonomy-mapping-form" onSubmit={submit}><label className="admin-field">Источник<select value={source} onChange={e => setSource(e.target.value)}>{aliasesOnly ? <option value="text_alias">Текстовый псевдоним</option> : <><option value="osm">OpenStreetMap</option><option value="wikidata">Wikidata</option><option value="legacy">Старая категория</option><option value="import">Источник импорта</option></>}</select></label><label className="admin-field">Ключ<input required value={key} onChange={e => setKey(e.target.value)} /></label><label className="admin-field">Значение<input required value={value} onChange={e => setValue(e.target.value)} /></label><label className="admin-field">Категория<select required value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Выберите</option>{categories.filter(row => row.is_active).map(row => <option value={row.id} key={row.id}>{row.display_name}</option>)}</select></label><button className="admin-btn admin-btn-primary">Добавить правило</button></form><div className="taxonomy-rule-list">{items.map(row => <article className="taxonomy-card" key={row.id}><strong>{row.source}: {row.source_key}={row.source_value}</strong><span>→ {categories.find(category => category.id === row.target_category_id)?.display_name || 'Категория удалена'}</span><button className="admin-btn admin-btn-sm" onClick={async () => { await adminPatch(`/admin/taxonomy/mappings/${row.id}`, { active: !row.active }); await load() }}>{row.active ? 'Отключить' : 'Включить'}</button></article>)}</div></section>
}

function ConflictsTab({ categories }: { categories: Category[] }) {
  const [items, setItems] = useState<Conflict[]>([]); const [severity, setSeverity] = useState(''); const load = useCallback(async () => { const data = await adminGet<{ items: Conflict[] }>(`/admin/taxonomy/conflicts?limit=50${severity ? `&severity=${severity}` : ''}`); setItems(data.items) }, [severity]); useEffect(() => { void load() }, [load])
  const resolve = async (row: Conflict, action: string, categoryId?: number) => { await adminPost(`/admin/taxonomy/conflicts/${row.id}/resolve`, { action, category_id: categoryId || row.recommended_category_id }); await load() }
  return <section><div className="taxonomy-toolbar"><select value={severity} onChange={e => setSeverity(e.target.value)}><option value="">Любая важность</option><option value="critical">Критично</option><option value="warning">Предупреждение</option></select><span className="admin-selection-count">{items.length} в очереди</span></div>{items.length === 0 ? <div className="admin-state">Активных конфликтов нет</div> : <div className="taxonomy-conflicts">{items.map(row => <article className="taxonomy-card taxonomy-conflict" key={row.id}><div><span className={`admin-badge severity-${row.severity}`}>{row.severity === 'critical' ? 'Критично' : 'Проверить'}</span><strong>{row.place_title || `Место #${row.place_id}`}</strong><p>{conflictLabel(row.conflict_type)}</p></div><div className="taxonomy-card-actions"><button className="admin-btn admin-btn-primary" disabled={!row.recommended_category_id} onClick={() => void resolve(row, 'accept')}>Принять рекомендацию</button><select aria-label="Выбрать категорию" defaultValue="" onChange={e => e.target.value && void resolve(row, 'choose', Number(e.target.value))}><option value="">Другая категория</option>{categories.filter(category => category.is_active).map(category => <option value={category.id} key={category.id}>{category.display_name}</option>)}</select><button className="admin-btn" onClick={() => void resolve(row, 'defer')}>Отложить</button><button className="admin-btn" onClick={() => void resolve(row, 'enrich')}>На обогащение</button></div></article>)}</div>}</section>
}

function BulkTab({ categories }: { categories: Category[] }) {
  const [city, setCity] = useState(''); const [oldCategory, setOldCategory] = useState(''); const [target, setTarget] = useState(''); const [updateRoutes, setUpdateRoutes] = useState(false); const [batch, setBatch] = useState<Batch | null>(null); const [busy, setBusy] = useState(false)
  const preview = async () => { setBusy(true); try { setBatch(await adminPost<Batch>('/admin/taxonomy/bulk/preview', { filters: { city_slug: city || undefined, category_id: oldCategory ? Number(oldCategory) : undefined }, target_category_id: Number(target), use_rule_engine: false, update_route_eligibility: updateRoutes, idempotency_key: crypto.randomUUID(), limit: 10000 })) } finally { setBusy(false) } }
  return <section className="taxonomy-bulk"><div className="admin-filter-card"><h2 className="admin-section-title">1. Выбор и dry-run</h2><div className="admin-filter-grid"><label className="admin-field">Город<input placeholder="slug города" value={city} onChange={e => setCity(e.target.value)} /></label><label className="admin-field">Текущая категория<select value={oldCategory} onChange={e => setOldCategory(e.target.value)}><option value="">Любая</option>{categories.map(row => <option value={row.id} key={row.id}>{row.display_name}</option>)}</select></label><label className="admin-field">Новая категория<select required value={target} onChange={e => setTarget(e.target.value)}><option value="">Выберите</option>{categories.filter(row => row.is_active).map(row => <option value={row.id} key={row.id}>{row.display_name}</option>)}</select></label><label className="taxonomy-check"><input type="checkbox" checked={updateRoutes} onChange={e => setUpdateRoutes(e.target.checked)} /> Явно обновить route eligibility</label></div><button className="admin-btn admin-btn-primary" disabled={!target || busy} onClick={() => void preview()}>{busy ? 'Считаем…' : 'Показать preview'}</button></div>{batch && <div className="admin-detail-panel"><h2 className="admin-section-title">2. Результат preview</h2><div className="admin-metrics-grid admin-metrics-small"><Metric label="Затронуто" value={batch.preview.count} /><Metric label="Конфликты маршрутов" value={batch.preview.route_conflicts} /></div><div className="taxonomy-examples">{batch.preview.examples.slice(0, 10).map((row, index) => <div key={index}><strong>{String(row.title)}</strong><span>{String(row.old_category || 'Без категории')} → {String(row.new_category)}</span></div>)}</div><div className="admin-sticky-actions"><span>Пакет {batch.id.slice(0, 8)}</span>{batch.status === 'preview' && <button className="admin-btn admin-btn-primary" onClick={async () => setBatch(await adminPost('/admin/taxonomy/bulk/apply', { batch_id: batch.id }))}>Применить изменения</button>}{batch.status === 'applied' && <button className="admin-btn admin-btn-danger" onClick={async () => setBatch(await adminPost(`/admin/taxonomy/bulk/${batch.id}/rollback`))}>Откатить пакет</button>}</div></div>}</section>
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="admin-metric-card"><div className="admin-metric-value">{value}</div><div className="admin-metric-label">{label}</div></div> }

function HistoryTab() { return <div className="admin-help-panel"><h2 className="admin-section-title">История решений</h2><p>Все изменения категорий, конфликты и массовые пакеты записываются в общий аудит с old/new значениями и actor.</p><Link className="admin-btn admin-btn-primary" to="/admin/audit?entity_type=category">Открыть журнал действий</Link></div> }

function RoutePoliciesTab({ categories, reload }: { categories: Category[]; reload: () => Promise<void> }) { return <div className="taxonomy-rule-list">{categories.map(row => <article className="taxonomy-card" key={row.id}><div><strong>{row.display_name}</strong><span>{row.is_catalog_visible ? 'В каталоге' : 'Скрыта в каталоге'}</span></div><select aria-label={`Политика ${row.display_name}`} value={row.route_policy} onChange={async e => { await adminPatch(`/admin/taxonomy/categories/${row.id}`, { route_policy: e.target.value, is_route_eligible: e.target.value !== 'forbidden' }); await reload() }}>{Object.entries(POLICY_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></article>)}</div> }
function conflictLabel(value: string) { const labels: Record<string, string> = { missing_category: 'Категория отсутствует', raw_backend_key: 'Пользователь увидит технический ключ', legacy_category: 'Используется старая категория', source_mismatch: 'Категория не совпадает с источником', infrastructure_attraction: 'Инфраструктура отмечена как достопримечательность', route_policy_mismatch: 'Конфликт политики маршрутов', ambiguous_rule: 'Неоднозначное правило', archived_category: 'Категория архивирована', suspicious_title: 'Подозрительное название', no_mapping: 'Нет подходящего сопоставления' }; return labels[value] || value }
