import models.admin_audit_log  # noqa: F401
import models.admin_operation  # noqa: F401
import models.feature_toggle  # noqa: F401
import models.product_event  # noqa: F401
import models.system_log  # noqa: F401
import models.category  # noqa: F401
import models.city  # noqa: F401
import models.city_candidate  # noqa: F401
import models.city_admin_import_job  # noqa: F401
import models.city_import_job  # noqa: F401
import models.city_import_scope  # noqa: F401
import models.city_scope_import_state  # noqa: F401
import models.collection  # noqa: F401
import models.collection_place  # noqa: F401
import models.country  # noqa: F401
import models.import_batch  # noqa: F401
import models.place_image  # noqa: F401
import models.place_verification  # noqa: F401
import models.place  # noqa: F401
import models.place_discovery_request  # noqa: F401
import models.place_import_event  # noqa: F401
import models.place_schedule  # noqa: F401
import models.place_scope_link  # noqa: F401
import models.place_source_presence  # noqa: F401
import models.place_tag  # noqa: F401
import models.place_verification_task  # noqa: F401
import models.region  # noqa: F401
import models.route  # noqa: F401
import models.route_build_event  # noqa: F401
import models.route_generation_run  # noqa: F401
import models.route_generation_candidate  # noqa: F401
import models.route_place  # noqa: F401
import models.source_observation  # noqa: F401
import models.tag  # noqa: F401
import models.telegram_user_context  # noqa: F401
import models.user_signal  # noqa: F401
